//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub messages: HasMany<super::messages::Entity>,
    #[sea_orm(has_many, via = "chat_members")]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
